#pragma once

#include "States\Karate01State.h"
#include "States\Karate02State.h"
#include "States\Karate03State.h"
#include "States\Karate04State.h"
#include "States\Karate05State.h"
#include "States\Karate06State.h"
#include "States\Karate07State.h"
#include "States\Karate08State.h"
#include "States\Karate09State.h"
#include "States\Karate10State.h"
#include "States\Karate11State.h"
#include "States\Karate12State.h"
#include "States\Karate13State.h"
#include "States\Karate14State.h"
#include "States\Karate15State.h"
#include "States\Karate16State.h"
#include "States\Karate17State.h"
#include "States\Karate18State.h"
#include "States\Karate19State.h"


/* ----------------------------------------------------------------------------
	Summary:
	Unique State ID values for each of the states.

---------------------------------------------------------------------------- */
enum
{
	STATEID_UNKNOWN = 0,

	STATEID_KARATE_FORWARD_KICK,
	STATEID_KARATE_02,
	STATEID_KARATE_03,
	STATEID_KARATE_04,
	STATEID_KARATE_05,
	STATEID_KARATE_06,
	STATEID_KARATE_07,
	STATEID_KARATE_08,
	STATEID_KARATE_09,
	STATEID_KARATE_10,
	STATEID_KARATE_11,
	STATEID_KARATE_12,
	STATEID_KARATE_13,
	STATEID_KARATE_14,
	STATEID_KARATE_15,
	STATEID_KARATE_16,
	STATEID_KARATE_17,
	STATEID_KARATE_18,
	STATEID_KARATE_19,

	STATEID_TOTAL
};



/* ----------------------------------------------------------------------------
	Summary:
	Description of the the unique state ID values.  Use the state ID as an
	index to referece the descriptions.  This table must sync up with the
	state ID enumeration list.

	In a tool chain, these values would be generated by a exporter.

---------------------------------------------------------------------------- */
static const char* StateIDDesc[] =
{
	{ "Unknown"},

	{ "Forward Kick" },
	{ "Side Kick" },
	{ "Spin Kick" },
	{ "Back Spin Kick 1" },
	{ "Back Spin Kick 2" },
	{ "Back Kick" },
	{ "Kakato Otoshi" },
	{ "Jab" },
	{ "Strong Punch" },
	{ "Punch" },
	{ "Punch Otherside" },
	{ "Double Punch" },
	{ "Back Knuckle" },
	{ "Spin Back Knuckle" },
	{ "Upper Guard" },
	{ "Inner Guard" },
	{ "Lower Guard" },
	{ "Chop Guard" },
	{ "Kata Variation" }
};



/* ----------------------------------------------------------------------------
	Summary:
	Return the state id description back to the caller

	Parameters:
	[in] id : state ID which you want to get a description of.
---------------------------------------------------------------------------- */
inline const char* GetStateIDDesc(int id)
{
	if (id < STATEID_TOTAL)
	{
		return StateIDDesc[id];
	}

	return StateIDDesc[0];
}



