#pragma once

#include "States\Karate01State.h"
#include "States\Karate02State.h"


enum
{
	STATEID_UNKNOWN = 0,
	STATEID_KARATE_01,
	STATEID_KARATE_02,
	STATEID_KARATE_03,
	STATEID_KARATE_04,
	STATEID_KARATE_05,
	STATEID_KARATE_06,
	STATEID_KARATE_07,
	STATEID_KARATE_08,
	STATEID_KARATE_09,
	STATEID_KARATE_10,
	STATEID_KARATE_11,
	STATEID_KARATE_12,
	STATEID_KARATE_13,
	STATEID_KARATE_14,
	STATEID_KARATE_15,
	STATEID_KARATE_16,
	STATEID_KARATE_17,
	STATEID_KARATE_18,
	STATEID_KARATE_19,
	STATEID_KARATE_TOTAL
};



